### ISSUE TITLE
Enh request - function to get ~ relative path

### ISSUE THREAD

**Issue by rkeithhill** [Jaykul/PowerLine#2]
When I'm in my home dir I want my paths to be shortened e.g.:

```
~\Documents\WindowsPowerShell
```

I could see a number of Path oriented commands like this including collapsing paths to a form like `C:\Git\...\src\PowerShellEditorServices.Protocol\DebugAdapter` to make a path fit within a certain number of characters.

**Comment by Jaykul** [comment]
Yeah, can you prototype something to do that?

I once thought about using "~" and any defined PSDrives ... and testing to see if `$pwd` starts with their root paths, and then replacing the string with that. Obviously as you've seen, I just settled for one folder name (because I use ZLocation, the folder name is the important thing), and putting the whole path in my title (or in my status bar, thank you conemu).

**Comment by rkeithhill** [comment]
In fact, I do have a prototype. Let me submit it as a PR tonight. It might be a good starting point so I won't hold it against you if you reject the PR.  But it's a start.  :-)

**Comment by gravejester** [comment]
Did anything come of this @rkeithhill ? If not, I think I have a path-shortener function that could be used for this.

**Comment by rkeithhill** [comment]
Yes, see #7

**Comment by gravejester** [comment]
Ah, I didn't look good enough then. Thanks. Oh well, I at least got inspired to add some more functionality to my function :)

**Comment by Jaykul** [comment]
There are two versions of this in the 2.3 release.

* Get-SegmentedPath (breaks each folder into a powerline segment, using the powerline separator, and has an option to limit the number of segments)
* Get-ShortenedPath (limits the total length of the path, and has an option to render each folder (except the last) as a single character instead of the real name)
