### ISSUE TITLE
Error with separator 

### ISSUE THREAD

**Issue by JM2K69** [Jaykul/PowerLine#56]
Hi 
I would like try this module but i have some trouble, I Install all module PANSIES, Powerline in scope CurrentUser. I also install  all PowerLine font with the powershell file.
I don't why i don't have the same separator like your picture. thx for your help.
It is the same way in the regular powershell console.

![Capture](https://user-images.githubusercontent.com/17923944/72726305-4f490d00-3b88-11ea-8189-ec885cdcdc7d.PNG)

**Comment by Jaykul** [comment]
You need to be _using_ a PowerLine font in Windows Terminal in order to use the `-PowerLineFont` switch.  The simplest thing is to choose a [NerdFont](https://www.nerdfonts.com/) (my current preference is "CaskaydiaCove Nerd Font Mono"). You can set it in the profile in the settings in Windows Terminal now:
![image](https://user-images.githubusercontent.com/192942/125573139-d856ff35-d8c0-4662-95e8-0e8b3fd0371f.png)
