### ISSUE TITLE
Exception in PowerLinePrompt

### ISSUE THREAD

**Issue by Swiftpaws** [Jaykul/PowerLine#64]
![image](https://user-images.githubusercontent.com/18440081/82299520-ea76b580-99b5-11ea-843c-8066aca975d2.png)

Tested with Powershell and Powershell 7

**Comment by Swiftpaws** [comment]
Workaround: Install version 1.4.0 of Pansies

`Install-Module -Name Pansies -RequiredVersion 1.4.0 -AllowClobber `

**Comment by RyanAmsbury** [comment]
I am also running into the same error. Removing the latest version of Pansies and installing 1.4.0 has worked around the issue.

**Comment by RyanAmsbury** [comment]
I am also getting the same error in PS 5.1 using Microsoft Terminal and ConEmu. Removing the latest Pansies and installing v1.4.0 has worked around the error.

**Comment by kmsOmega** [comment]
It took me a long time to find this issue because the searching the site for `Unable to find type [PoshCode.Pansies.Console.WindowsHelper]` did not return the text from the screenshot. Now that I'm here, it appears that the PoshCode/Pansies/Source/Assembly/NativeMethods.cs script moved the EnableVirtualTerminalProcessing function from `[PoshCode.Pansies.Console.WindowsHelper]` to `[PoshCode.Pansies.NativeMethods+ConsoleOutputModes]`.

**Comment by JM2K69** [comment]
> It took me a long time to find this issue because the searching the site for `Unable to find type [PoshCode.Pansies.Console.WindowsHelper]` did not return the text from the screenshot. Now that I'm here, it appears that the PoshCode/Pansies/Source/Assembly/NativeMethods.cs script moved the EnableVirtualTerminalProcessing function from `[PoshCode.Pansies.Console.WindowsHelper]` to `[PoshCode.Pansies.NativeMethods]`.
> 
> Edit 0: Corrected `[PoshCode.Pansies.NativeMethods+ConsoleOutputModes]` to `[PoshCode.Pansies.NativeMethods]`.
> Edit 1: PowerLine file: [Source/Public/Write-PowerlinePrompt.ps1 - Line 30](https://github.com/Jaykul/PowerLine/blob/master/Source/Public/Write-PowerlinePrompt.ps1#L30)

I work's Great.

**Comment by Jaykul** [comment]
I'm so sorry about this, folks! I have apparently been missing my notifications again.

I completely screwed up when I changed that class name. I didn't notice because I have been running with `RestoreVirtualTerminal` turned off (as far as I can tell, we don't need to do that every command anymore). You can do so too by running:

```PowerShell
Set-PowerLinePrompt -RestoreVirtualTerminal:$false
```

Now that I've seen this, I'll get a fix out ASAP (and I'll see about some of these other issues too, wow).

**Comment by kmsOmega** [comment]
@Jaykul - No worries - I have been using PowerLine (as well as Pansies) since I wrote that post two weeks ago and it is intuitive, looks amazing, and provides me with a number of useful pieces of information with each command that I execute. Thank you very much for sharing this!

**Comment by Jaykul** [comment]
I believe this is done -- although I do have more releases of all of these still in the pipeline (so to speak)
